application: gae-workers-shell-demo
version: demo
runtime: python27
threadsafe: true
api_version: 1


libraries:
- name: jinja2
  version: latest


handlers:

- url: /_ah/worker
  script: ../gaeworkers/runner.py
  
- url: /.*
  script: shell.app